# Generated by Django 5.0.3 on 2025-04-27 23:18

import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.CharField(default=research.models.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(default='processing', max_length=100)),
                ('model', models.CharField(default='gemini-1.5-pro', max_length=100)),
                ('search_model', models.CharField(blank=True, max_length=100, null=True)),
                ('max_searches', models.IntegerField(default=5)),
                ('custom_requirement', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('_learnings', models.TextField(blank=True, db_column='learnings', default='[]')),
            ],
        ),
    ]
